In [ ]:
# !pip install fasttext
# !pip install gensim

In [1]:
import gensim 
import logging



* INTERVIEW: NPR Media Dialog Transcripts

https://www.kaggle.com/datasets/shuyangli94/interview-npr-media-dialog-transcripts/

* Data consists of 140K+ NPR radio transcripts (from npr.org) covering 20 years of NPR programs, comprising the transcriptions of 10K+ hours of audio. It is introduced and used in the following papers (please cite them if you use this dataset!)


In [22]:

with open("./media/npr_1000_utterances.csv", 'r') as f:
    i = 0 
    for i,line in enumerate (f):
        print(line)
        if i ==3:
            break
        i += 1
        

episode,episode_order,speaker,utterance

57264,9,"Ms. LOREN MOONEY (Editor-in-Chief, Bicycling Magazine)","It's a 2,200-mile race. To give some sense of perspective, that's roughly the distance between Washington, D.C. and Las Vegas. They do it over the course of three weeks at very fast speeds. But incredibly, oftentimes the distance between first and second is somewhere between and one and three minutes."

57264,10,"Ms. LOREN MOONEY (Editor-in-Chief, Bicycling Magazine)","So for a top competitor like Lance to try to make up that much time -he's now 13 minutes, 26 seconds behind the current race leader, Cadel Evans of Australia. And even Lance said yesterday that for him, the -any chance of winning the tour has gone out the window. He still does have a teammate on his team, RadioShack team, American Levi Leipheimer currently in eighth place, two minutes, 14 seconds back. And Lance is going to do what he can to help Leipheimer do well."

57264,11,"NEAL CONAN, host","So in every team, p

In [3]:
input_file

'./media/npr_1000_utterances.csv'

In [23]:
import csv
reader = csv.reader(open("./media/npr_1000_utterances.csv"), delimiter=',', quotechar='"')
for row in reader:
    print(row)
    break

['episode', 'episode_order', 'speaker', 'utterance']


In [24]:
def read_input(input_file):
    utterances = []
    with open(input_file, newline='', encoding='utf-8') as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        next(reader, None)
        for row in reader:
            text = row[-1]  
            yield gensim.utils.simple_preprocess(text)  # Yield the preprocessed text

utterances = list(read_input("./media/npr_1000_utterances.csv"))


In [25]:
utterances


[['it',
  'mile',
  'race',
  'to',
  'give',
  'some',
  'sense',
  'of',
  'perspective',
  'that',
  'roughly',
  'the',
  'distance',
  'between',
  'washington',
  'and',
  'las',
  'vegas',
  'they',
  'do',
  'it',
  'over',
  'the',
  'course',
  'of',
  'three',
  'weeks',
  'at',
  'very',
  'fast',
  'speeds',
  'but',
  'incredibly',
  'oftentimes',
  'the',
  'distance',
  'between',
  'first',
  'and',
  'second',
  'is',
  'somewhere',
  'between',
  'and',
  'one',
  'and',
  'three',
  'minutes'],
 ['so',
  'for',
  'top',
  'competitor',
  'like',
  'lance',
  'to',
  'try',
  'to',
  'make',
  'up',
  'that',
  'much',
  'time',
  'he',
  'now',
  'minutes',
  'seconds',
  'behind',
  'the',
  'current',
  'race',
  'leader',
  'cadel',
  'evans',
  'of',
  'australia',
  'and',
  'even',
  'lance',
  'said',
  'yesterday',
  'that',
  'for',
  'him',
  'the',
  'any',
  'chance',
  'of',
  'winning',
  'the',
  'tour',
  'has',
  'gone',
  'out',
  'the',
  'window'

In [8]:
model = gensim.models.Word2Vec(utterances, window=10, min_count=2, workers=10)
model

In [9]:
model.wv.key_to_index 

{'the': 0,
 'and': 1,
 'of': 2,
 'to': 3,
 'that': 4,
 'in': 5,
 'you': 6,
 'it': 7,
 'is': 8,
 'they': 9,
 'we': 10,
 'for': 11,
 'this': 12,
 'on': 13,
 'are': 14,
 'was': 15,
 'have': 16,
 'he': 17,
 'so': 18,
 'be': 19,
 'there': 20,
 'with': 21,
 'but': 22,
 'know': 23,
 'what': 24,
 'as': 25,
 'not': 26,
 'about': 27,
 're': 28,
 'do': 29,
 'think': 30,
 'or': 31,
 'who': 32,
 'people': 33,
 'at': 34,
 'from': 35,
 'can': 36,
 'just': 37,
 'like': 38,
 'very': 39,
 'us': 40,
 'one': 41,
 'if': 42,
 'well': 43,
 'has': 44,
 'some': 45,
 'their': 46,
 'an': 47,
 'all': 48,
 'when': 49,
 'much': 50,
 'these': 51,
 'by': 52,
 'his': 53,
 'them': 54,
 'more': 55,
 'out': 56,
 'how': 57,
 'because': 58,
 'would': 59,
 'don': 60,
 'now': 61,
 'really': 62,
 'right': 63,
 'been': 64,
 'talk': 65,
 'here': 66,
 'get': 67,
 'time': 68,
 'had': 69,
 'case': 70,
 'public': 71,
 'other': 72,
 'npr': 73,
 'up': 74,
 'our': 75,
 'your': 76,
 'were': 77,
 'see': 78,
 'said': 79,
 'those': 80,
 '

In [26]:
model = gensim.models.Word2Vec(utterances, window=10, min_count=2, workers=10)

In [30]:
model.wv["war"].size

100

In [31]:
w1 = ["war"]
model.wv.most_similar (positive=w1, topn=6)

[('us', 0.9994051456451416),
 ('into', 0.9993998408317566),
 ('with', 0.9993917346000671),
 ('time', 0.9993862509727478),
 ('that', 0.9993810653686523),
 ('new', 0.9993647933006287)]

### Some issues with the embeddings

The models learn what's in the data:

1. Data may contain errors, biases, and inaccuracies

2. The similarity may not always be intuitive

3. The results will contain inaccuracies

In [32]:
utterances = list(read_input("./media/npr_100000_utterances.csv"))
model = gensim.models.Word2Vec(utterances, window=10, min_count=2, workers=10)
model

In [34]:
w1 = ["peace"]
model.wv.most_similar (positive=w1,topn=6)

[('hamas', 0.7439557909965515),
 ('israel', 0.7426904439926147),
 ('diplomatic', 0.7363422513008118),
 ('palestinian', 0.7238703966140747),
 ('resolution', 0.7224636077880859),
 ('negotiations', 0.7209641337394714)]

In [36]:
w1 = ["france"]
model.wv.most_similar (positive=w1,topn=6)

[('britain', 0.8055888414382935),
 ('paris', 0.8050899505615234),
 ('jordan', 0.7818824052810669),
 ('kenya', 0.770249605178833),
 ('berlin', 0.7641852498054504),
 ('georgia', 0.75344318151474)]

In [20]:
w1 = ["clean"]
model.wv.most_similar (positive=w1,topn=6)

[('wind', 0.7188198566436768),
 ('speed', 0.6728765964508057),
 ('coal', 0.6722075939178467),
 ('radioactive', 0.6681318283081055),
 ('prop', 0.6629115343093872),
 ('carbon', 0.66191565990448)]

### Facebook's FastText
```FastText is an open-source, free, lightweight library that allows users to learn text representations and text classifiers. It works on standard, generic hardware. Models can later be reduced in size to even fit on mobile devices.```



![](https://www.dropbox.com/s/i74guibnv5mxx2h/fasttext.png?dl=1)

https://fasttext.cc/

In [1]:
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip


--2023-10-24 08:58:21--  https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 2600:9000:201d:d800:13:6e38:acc0:93a1, 2600:9000:201d:5600:13:6e38:acc0:93a1, 2600:9000:201d:4200:13:6e38:acc0:93a1, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|2600:9000:201d:d800:13:6e38:acc0:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 681808098 (650M) [application/zip]
Saving to: ‘wiki-news-300d-1M.vec.zip’

wiki-news-300d-1M.v 100%[===================>] 650.22M  28.9MB/s    in 22s     

2023-10-24 08:58:43 (29.6 MB/s) - ‘wiki-news-300d-1M.vec.zip’ saved [681808098/681808098]



In [ ]:
!mv wiki-news-300d-1M.vec.zip media/
!unzip -f media/wiki-news-300d-1M.vec.zip


In [38]:
keep_words= [x.rstrip() for x in open("./media/words_to_keep")]
keep_words

--2023-10-11 22:43:29--  https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 2600:9000:20a6:e400:13:6e38:acc0:93a1, 2600:9000:20a6:e200:13:6e38:acc0:93a1, 2600:9000:20a6:a00:13:6e38:acc0:93a1, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|2600:9000:20a6:e400:13:6e38:acc0:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 681808098 (650M) [application/zip]
Saving to: ‘wiki-news-300d-1M.vec.zip’

wiki-news-300d-1M.v 100%[===================>] 650.22M  27.2MB/s    in 25s     

2023-10-11 22:43:55 (25.9 MB/s) - ‘wiki-news-300d-1M.vec.zip’ saved [681808098/681808098]



['Athens',
 'Greece',
 'Bangkok',
 'Thailand',
 'Latvia',
 'lats',
 'Bulgaria',
 'lev',
 'bad',
 'worse',
 'big',
 'bigger',
 'boy',
 'girl',
 'brother',
 'sister']

In [46]:
import numpy as np
words_embeds = {}
for line in open("wiki-news-300d-1M.vec"):
    data = line.split()
    if data[0] in keep_words:
        words_embeds[data[0]] = np.array(list(map(float, data[1:])))


In [50]:
words_embeds["big"].size


300

In [51]:
words_embeds.keys()

dict_keys(['big', 'bad', 'girl', 'Greece', 'boy', 'brother', 'worse', 'sister', 'bigger', 'Thailand', 'Bulgaria', 'Athens', 'Latvia', 'Bangkok', 'lats', 'lev'])

In [52]:
res = words_embeds["girl"] - words_embeds["boy"] + words_embeds["brother"]
res

array([ 0.3193, -0.0592, -0.0461, -0.1192, -0.0269,  0.0761, -0.0135,
       -0.0527, -0.0506,  0.073 ,  0.0514, -0.1087,  0.0921, -0.0437,
        0.0175,  0.204 , -0.0187, -0.0671,  0.1144, -0.0361, -0.1047,
        0.1144, -0.2408,  0.0436,  0.0406, -0.0068, -0.1024,  0.1106,
       -0.0419, -0.1826,  0.1547,  0.0084, -0.2653,  0.1108, -0.1934,
        0.152 , -0.1   , -0.0516,  0.0547, -0.0557, -0.0244,  0.1113,
       -0.0535,  0.0241,  0.0024, -0.0016, -0.0264,  0.0544,  0.0263,
       -0.0619,  0.0101, -0.0284, -0.6605,  0.12  ,  0.051 , -0.0162,
       -0.0769,  0.1983,  0.0784,  0.0058,  0.0147, -0.0124, -0.0843,
       -0.076 , -0.0489, -0.0935, -0.0857,  0.113 ,  0.0732, -0.0112,
        0.0516, -0.0555, -0.026 ,  0.0495, -0.0793,  0.1126,  0.0691,
        0.1725, -0.0754,  0.049 ,  0.036 , -0.1203, -0.0533, -0.185 ,
        0.108 , -0.073 , -0.2247, -0.2533,  0.1525,  0.0283, -0.0906,
        0.1891,  0.0952, -0.0831,  0.1297,  0.1307, -0.0464,  0.0717,
        0.0647, -0.0

In [56]:
(res - words_embeds["sister"]).round(2)

array([ 0.09,  0.03, -0.02, -0.01,  0.06,  0.  , -0.03, -0.1 , -0.18,
        0.05,  0.08,  0.09,  0.15, -0.  , -0.02,  0.12, -0.15, -0.14,
        0.08,  0.1 , -0.11,  0.09, -0.12, -0.12,  0.04,  0.05, -0.  ,
       -0.  , -0.04, -0.11, -0.03, -0.03, -0.06,  0.02, -0.13,  0.05,
       -0.13,  0.04, -0.01, -0.03,  0.11,  0.03,  0.07,  0.01,  0.1 ,
        0.  ,  0.02,  0.06,  0.1 , -0.07,  0.02,  0.05, -0.02,  0.12,
        0.07, -0.04, -0.01, -0.03,  0.01, -0.04,  0.03, -0.17,  0.02,
        0.04, -0.16,  0.11, -0.03,  0.05, -0.06,  0.03, -0.05, -0.07,
        0.03, -0.  , -0.08, -0.05,  0.06,  0.1 , -0.01,  0.08,  0.01,
       -0.07,  0.02,  0.03,  0.08, -0.14, -0.11, -0.12,  0.03,  0.05,
        0.02,  0.05,  0.03, -0.02,  0.08, -0.02, -0.06,  0.09,  0.07,
        0.02, -0.  ,  0.1 , -0.  ,  0.06, -0.06, -0.09, -0.  , -0.08,
       -0.04,  0.1 , -0.07,  0.08,  0.1 ,  0.02, -0.  , -0.03, -0.22,
       -0.06, -0.05, -0.07,  0.04, -0.01,  0.06, -0.  ,  0.01,  0.04,
       -0.01,  0.05,

In [57]:
words_embeds["big"] - words_embeds["bigger"]

array([-0.1327,  0.0784, -0.055 ,  0.0611,  0.0797,  0.1164,  0.046 ,
       -0.037 , -0.0355,  0.0513, -0.0199, -0.0035, -0.0899, -0.1537,
        0.1146, -0.0609, -0.0377,  0.0771,  0.1355, -0.0447,  0.0406,
        0.0276, -0.0242, -0.1399, -0.015 , -0.017 ,  0.0434,  0.1223,
       -0.1286, -0.0405, -0.0133,  0.0051,  0.148 , -0.0099, -0.0094,
       -0.0259, -0.0225, -0.0012,  0.0467,  0.0649, -0.0056, -0.1069,
       -0.0731, -0.0892,  0.0733, -0.147 , -0.0383, -0.021 , -0.0656,
       -0.0414,  0.0473, -0.1991,  0.0511, -0.1198, -0.0425,  0.0225,
        0.0601, -0.0004,  0.1398, -0.1176,  0.0966, -0.0023, -0.0718,
       -0.1041, -0.0655,  0.0543, -0.0539, -0.0064,  0.014 , -0.0332,
        0.0053, -0.005 ,  0.0586, -0.0089, -0.0059,  0.0169,  0.0279,
        0.0184, -0.0467, -0.1185,  0.0281, -0.1469,  0.0144, -0.0349,
       -0.029 , -0.0187,  0.0252,  0.0442,  0.0651, -0.029 , -0.0815,
        0.0467, -0.067 ,  0.0571,  0.0345, -0.0431,  0.036 , -0.0751,
        0.0092, -0.0

In [58]:
words_embeds["bad"] - words_embeds["worse"]

array([-0.0787,  0.0242, -0.1185, -0.0537,  0.043 , -0.0393,  0.0571,
        0.0376, -0.0712,  0.0804, -0.0086, -0.0253, -0.0076, -0.0387,
        0.0228, -0.0386, -0.1761,  0.1261, -0.1006, -0.0851, -0.0035,
        0.0702,  0.0701, -0.032 , -0.1056, -0.0551, -0.0382,  0.0622,
       -0.1478,  0.0503, -0.0453,  0.0566,  0.1311,  0.1304, -0.0086,
       -0.0209, -0.1283,  0.0258, -0.0828,  0.1165,  0.031 ,  0.0346,
       -0.166 , -0.0239, -0.0041,  0.0102,  0.1294, -0.0491,  0.0247,
       -0.0963,  0.0205, -0.125 , -0.0094, -0.0271, -0.0095, -0.0034,
        0.0866, -0.0041,  0.1393, -0.1289,  0.0528,  0.0063, -0.1536,
       -0.0411,  0.0974,  0.2016, -0.0616,  0.0381,  0.0947, -0.0441,
        0.0408,  0.0899, -0.0282,  0.0379,  0.0183,  0.0029,  0.0329,
        0.0653,  0.1541, -0.0011,  0.0159, -0.0963,  0.1247, -0.0394,
        0.0224,  0.0022, -0.0763, -0.0646,  0.2064,  0.1143, -0.0372,
        0.0529,  0.0101,  0.0577,  0.0126,  0.0242,  0.0227,  0.0749,
        0.0312, -0.0

In [59]:
(words_embeds["bad"] - words_embeds["worse"]) - (words_embeds["big"] - words_embeds["bigger"])

array([ 5.400e-02, -5.420e-02, -6.350e-02, -1.148e-01, -3.670e-02,
       -1.557e-01,  1.110e-02,  7.460e-02, -3.570e-02,  2.910e-02,
        1.130e-02, -2.180e-02,  8.230e-02,  1.150e-01, -9.180e-02,
        2.230e-02, -1.384e-01,  4.900e-02, -2.361e-01, -4.040e-02,
       -4.410e-02,  4.260e-02,  9.430e-02,  1.079e-01, -9.060e-02,
       -3.810e-02, -8.160e-02, -6.010e-02, -1.920e-02,  9.080e-02,
       -3.200e-02,  5.150e-02, -1.690e-02,  1.403e-01,  8.000e-04,
        5.000e-03, -1.058e-01,  2.700e-02, -1.295e-01,  5.160e-02,
        3.660e-02,  1.415e-01, -9.290e-02,  6.530e-02, -7.740e-02,
        1.572e-01,  1.677e-01, -2.810e-02,  9.030e-02, -5.490e-02,
       -2.680e-02,  7.410e-02, -6.050e-02,  9.270e-02,  3.300e-02,
       -2.590e-02,  2.650e-02, -3.700e-03, -5.000e-04, -1.130e-02,
       -4.380e-02,  8.600e-03, -8.180e-02,  6.300e-02,  1.629e-01,
        1.473e-01, -7.700e-03,  4.450e-02,  8.070e-02, -1.090e-02,
        3.550e-02,  9.490e-02, -8.680e-02,  4.680e-02,  2.420e

In [60]:
# https://github.com/facebookresearch/faiss
# !pip install faiss


In [61]:
import faiss

In [88]:
words = np.array(list(words_embeds.keys()))
embeds = np.array(list(words_embeds.values()))

In [75]:
index = faiss.IndexFlatL2(300)
index.add(embeds)   

In [80]:
np.array([words_embeds["bad"]])

array([[ 3.180e-02, -1.105e-01, -1.446e-01, -3.510e-02, -4.610e-02,
         6.990e-02,  4.390e-02, -4.310e-02,  7.330e-02, -6.790e-02,
         7.900e-03, -1.142e-01, -3.660e-02, -3.880e-02, -8.730e-02,
         1.160e-02, -1.213e-01,  7.770e-02,  1.200e-03, -9.450e-02,
         8.100e-03,  7.300e-03,  4.880e-02,  1.211e-01, -2.710e-02,
        -1.052e-01, -4.690e-02, -6.370e-02, -4.960e-02, -1.770e-02,
         4.860e-02, -3.890e-02,  2.301e-01,  1.047e-01,  8.890e-02,
         1.141e-01, -2.470e-02, -5.620e-02, -6.120e-02,  9.820e-02,
         1.081e-01,  6.760e-02, -1.718e-01, -1.690e-02, -1.780e-02,
        -6.100e-03,  3.450e-02,  8.070e-02,  1.600e-02,  2.320e-02,
         4.800e-02, -9.170e-02, -7.630e-01, -4.980e-02,  3.170e-02,
        -3.420e-02,  1.029e-01,  2.180e-02,  6.800e-03, -5.440e-02,
        -1.476e-01, -2.400e-03,  3.340e-02, -5.610e-02,  1.173e-01,
        -1.176e-01,  2.580e-02,  9.420e-02, -5.800e-02,  1.440e-02,
        -2.730e-02,  5.440e-02, -6.590e-02, -8.3

In [81]:
index.search(np.array([words_embeds["bad"]]), k=3)

(array([[0.       , 2.598906 , 3.0293205]], dtype=float32), array([[1, 6, 0]]))

In [87]:
words

array(dict_keys(['big', 'bad', 'girl', 'Greece', 'boy', 'brother', 'worse', 'sister', 'bigger', 'Thailand', 'Bulgaria', 'Athens', 'Latvia', 'Bangkok', 'lats', 'lev']),
      dtype=object)

In [ ]:
words[0]

In [ ]:
index.is_trained

### Demo from Faiss: The Missing Manual
- Demo posted on Pinecone's website

  - [Faiss: The Missing Manual](https://www.pinecone.io/learn/series/faiss/faiss-tutorial/)